[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.57.2"
HUGO_ENABLEGITINFO = "true"

[context.production.environment]
HUGO_VERSION = "0.57.2"
HUGO_ENV = "production"
